### ISSUE TITLE
[High] Constants in equality constraints

### ISSUE THREAD

**Issue by ShreyanJabade** [fvutils/pyvsc#82]
Hello,
Suppose we define a and b as uint8 and attempt to write self.a*self.b == num, there is a "solve failure" error whenever num > 255. In the snippet below, self.a * self.b == 256 gives solve failure even though (128, 2) is a valid solution.
I request you to look into this aspect.
Thank you

```
import vsc
import random
random.seed(0)

@vsc.randobj
class Test:
    def __init__(self):
        self.a = vsc.rand_uint8_t()
        self.b = vsc.rand_uint8_t()
        self.c = vsc.rand_uint8_t()

    @vsc.constraint
    def test_c(self):
        # Error
        self.a*self.b == 256

        # Works
        #self.a*self.b < 256

inst = Test()
inst.randomize()
print("a =", inst.a, "b =", inst.b)

```

Output is:

```
Problem Constraints:
Constraint 1:
((a * b) == 256);
((a * b) == 256);
solve failure
```

**Comment by mballance** [comment]
After investigating, I found that both this issue and #81 are due to context-dependent expression widths not being properly accounted for. In the example above, the width of the multiplication result is 8 bits (the max width of the two operands). However, the context is 32-bit due to the presence of the literal. The expected result is that the width of the multiplication result will be 32-bit as well.
I've made a fix in 0.4.3 that resolves this for the testcases in #81 and #82. I'll leave this open until you can confirm that it works for you.
